### ISSUE TITLE
6-DOF-AUV position and speed control of some reference data problems in this project

### ISSUE THREAD

**Issue by Hhuluwa** [AmoghJuloori/Position-and-Velocity-Control-of-a-6-DOF-AUV#1]
Hello author, I am interested in your project and I am also studying your report now, but I would like to know where the data in your project came from. Are there any references or given titles that contain these data? If so, could you share with me? Thank you very much

**Comment by AmoghJuloori** [comment]
Hello @Hhuluwa , thank you for your interest in the project. To the best of my knowledge, the data included in the report is either taken from one of the references ([6-DoF Modelling and Control of a Remotely Operated Vehicle](https://flex.flinders.edu.au/file/27aa0064-9de2-441c-8a17-655405d5fc2e/1/ThesisWu2018.pdf)) stated at the end or a part of our own experimental results. You can also check out the  other documentation from BlueROV for other related details. 
Hope this helps!

**Comment by Hhuluwa** [comment]
Hello author, I'm sorry to bother you again, in your PID linear module, I would like to ask you a few questions, the first question is why in the dynamics module where the input of velocity is the order of vv(1)vv(1)vv(1)vv(2)vv(4)vv(5)vv(6), instead of the order of vv(1)vv(2)vv(3)vv(4)vv(5)vv(6), shouldn't it be the order of uvwpqr? If you change the order to the latter, it will not work properly. The second question is whether the expectations given are obtained through your own experiments, and the results of my change of values do not seem to be very stable, or even impossible.Can I add your contact information, I want to continue to ask you if I have any questions later

**Comment by AmoghJuloori** [comment]
Hey @Hhuluwa , I apologise for the late response. As for your first question, I checked the model and even I am not sure about the reason behind the order of the input velocities - it seems to be a mistake but I'll have to look into it. But since the PID is simply an implementation of the paper, it should work once you fine tune it. Regarding the expectations, as per my knowledge we had given random values as expectations and generated the graphs so it should work. I'll modify the model and update it if possible. Thanks for your questions! In case you are still interested in the project, you can contact me at [ julooriamogh@gmail.com ](mailto:julooriamogh@gmail.com)
